version: '3'

services:  
  app:    
    build:      
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - RAILS_MASTER_KEY ${RAILS_MASTER_KEY}
  web:    
    build:      
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:      
      - app    
    ports:      
      - ${PORT}:80
