version: '3'

services:  
  app:    
    build:      
      context: .
      dockerfile: ./docker/app/Dockerfile
  web:    
    build:      
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:      
      - app    
    ports:      
      - ${PORT:-80}:80
